### ISSUE TITLE
Driver App UI

### ISSUE THREAD

**Issue by jayportimo** [AWAP-6/driverAppUI#1]
## Task list:

- [ ] Create a header

### Parcel locker location

- [ ] Create buttons from 1 to 5
- [ ] Clicking a button opens up a popup view on top of the existing page of that specific locations lockers
- [ ] Clicking outside of the popup closes it and driver is back to default

### Popup view specific to clicked location

- [ ] Create a list with all specific locations lockers 

#### Status, number and open code fetched from database

- [ ] Visualize coloured dots (red, yellow, green) to symbolize that lockers status 
- [ ] Status needs to be written as well
- [ ] Locker names/numbers need to be visible
- [ ] Code for opening locker visible
- [ ] Red coloured lockers need to have buttons for the driver to change the status when picked up for delivery or ready to be picked up by customer
- [ ] When toggled, needs to send notification to sender or recipient
